# Export to Clips deffacts
This notebook shall hold the code to read in the webscraped csv and export into the deffacts clips format. <br>
It will be exported in a .txt file so that the user can easily copy and paste it in the .clp file

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('FinalGivingSGScrape20Feb.csv')

In [3]:
df.head()

,Organisation,Event Name,Day,Start Date,Last Date,Duration (Hours),Weekend/Weekday/Anyday,Location,Cause1,Cause2,...,Skills1,Skills2,Skills3,Suitability1,Suitability2,Suitability3,Suitability4,Min Age,Openings,Corporate Friendly (>10 openings)
0,Metta Welfare Association,Volunteer Photographer for Metta Charity Golf ...,Fri,27 Jul 2018,Ad Hoc,10.0,Weekday,Seletar,Children & Youth,Disability,...,Other Skills,NaN,NaN,Open to All,NaN,NaN,NaN,22,2,NoCSR
1,Morning Star Community Services Ltd.,CareNights @ Sengkang,Wed,3 Jan 2018,31 Aug 2018,2.0,Weekday,Bedok,Children & Youth,Community,...,Coaching & Training,Other Skills,NaN,Open to All,NaN,NaN,NaN,17,13,CSR
2,Yishun Community Hospital,"Mobile Library in the wards (Every Wednesday, ...",Wed,15 Nov 2017,26 Dec 2018,2.0,Weekday,Yishun,Community,Education,...,No Specific Skills Required,NaN,NaN,Open to All,NaN,NaN,NaN,13,15,CSR
3,All Saints Home,Be an All Saints Home Volunteer!,Sat,17 Nov 2018,Ad Hoc,2.5,Weekend,Yishun,Community,Elderly,...,No Specific Skills Required,NaN,NaN,First Timers,Seniors,Open to All,Family Friendly,13,499,CSR
4,AMKFSC Community Services,Bringing Joy to our Seniors - Senior Activity ...,Tue,2 Jan 2018,30 Jun 2018,2.0,Weekday,Punggol,Community,Elderly,...,Arts & Music,Coaching & Training,NaN,Open to All,NaN,NaN,NaN,16,15,CSR

In [5]:
df.columns

Index(['Organisation', 'Event Name', 'Day', 'Start Date', 'Last Date',
       'Duration (Hours)', 'Weekend/Weekday/Anyday', 'Location', 'Cause1',
       'Cause2', 'Cause3', 'Skills1', 'Skills2', 'Skills3', 'Suitability1',
       'Suitability2', 'Suitability3', 'Suitability4', 'Min Age', 'Openings',
       'Corporate Friendly (>10 openings)'],
      dtype='object')

In [33]:
f = open("Output.txt", "w")

In [30]:
for i in range(len(df[:1])):
    print('''(event (name-org "{}-{}") (start-date "{}") (end-date "{}") (duration {}) 
         (wkend-wkday-any "{}") (location "{}") (min-age {}) (opening {})
         (cause "{}" "{}" "{}") (skill "{}" "{}" "{}") (suitability "{}" "{}" "{}" "{}"))'''.format(df['Event Name'][i], 
                                                                                 df['Organisation'][i], 
                                                                                 df['Start Date'][i],
                                                                                df['Last Date'][i],
                                                                                df['Duration (Hours)'][i],
                                                                                df['Weekend/Weekday/Anyday'][i],
                                                                                df['Location'][i],
                                                                                 df['Min Age'][i],
                                                                                 df['Openings'][i],
                                                                                df['Cause1'][i],
                                                                                df['Cause2'][i],
                                                                                df['Cause3'][i],
                                                                                df['Skills1'][i],
                                                                                df['Skills2'][i],
                                                                                df['Skills3'][i],
                                                                                df['Suitability1'][i],
                                                                                df['Suitability2'][i],
                                                                                df['Suitability3'][i],
                                                                                df['Suitability4'][i]))

(event (name-org "Volunteer Photographer for Metta Charity Golf Tournament 2018-Metta Welfare Association") (start-date " 27 Jul 2018") (end-date "Ad Hoc") (duration 10.0)
         (wkend-wkday-any "Weekday" (location "Seletar") (min-age 22) (opening 2)
         (cause "Children & Youth" "Disability" "Elderly") (skill " Other Skills" "nan" "nan") (suitability " Open to All" "nan" "nan" "nan")))

In [34]:
for i in range(len(df)):
    f.write('''(event (name-org "{}-{}") (start-date "{}") (end-date "{}") (duration {}) 
         (wkend-wkday-any "{}") (location "{}") (min-age {}) (opening {})
         (cause "{}" "{}" "{}") (skill "{}" "{}" "{}") (suitability "{}" "{}" "{}" "{}"))\n'''.format(df['Event Name'][i], 
                                                                                 df['Organisation'][i], 
                                                                                 df['Start Date'][i],
                                                                                df['Last Date'][i],
                                                                                df['Duration (Hours)'][i],
                                                                                df['Weekend/Weekday/Anyday'][i],
                                                                                df['Location'][i],
                                                                                 df['Min Age'][i],
                                                                                 df['Openings'][i],
                                                                                df['Cause1'][i],
                                                                                df['Cause2'][i],
                                                                                df['Cause3'][i],
                                                                                df['Skills1'][i],
                                                                                df['Skills2'][i],
                                                                                df['Skills3'][i],
                                                                                df['Suitability1'][i],
                                                                                df['Suitability2'][i],
                                                                                df['Suitability3'][i],
                                                                                df['Suitability4'][i]))
f.close()